<div class="form-group">
	<label for="type">Contact type:*</label>
	<div class="input-group">
	    <span class="input-group-addon">
	        <i class="fa fa-user"></i>
	    </span>
	    <select class="form-control valid" id="contact_type" required="" name="type">
	    	<option value="supplier" {{ $contact_type == 'supplier' ? 'selected' : '' }}>Suppliers</option>
	    	<option value="customer" {{ $contact_type == 'customer' ? 'selected' : '' }}>Customers</option>
	    </select>
	</div>
</div>
<div class="form-group">
	<label for="contact_name">Name*</label>
	<input type="text" class="form-control" name="contact_name" id="contact_name">
</div>

<div class="form-group">
	<label for="contact_id">{{ ucfirst($contact_type). " ID" }}:*</label>
	<input type="text" class="form-control" name="contact_id" id="contact_id" value="{{ $auto_cont_id }}" >
	<p class="help-block">ID is automatic generated by this system</p>
</div>

<div class="form-group">
	<label for="email">E-mail:</label>
	<input type="email" class="form-control" name="email" id="email">
</div>
<div class="form-group">
	<label for="phone">Phone:</label>
	<input type="text" class="form-control" name="phone" id="phone">
</div>
<div class="form-group">
	<label for="cont">Country:</label>
	<input type="text" class="form-control" name="country" id="cont">
</div>
<div class="form-group">
	<label for="city">City:</label>
	<input type="text" class="form-control" name="city" id="city">
</div>

<div class="form-group">
	<label for="des">Notes:</label>
	<textarea name="notes" id="des" cols="20" rows="5" class="form-control"></textarea>
</div>